version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DB_UNO_ONLINE
    volumes:
      - './data/:/var/lib/postgresql/data/'
